# Generated by Django 4.1 on 2022-08-20 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6363da80-b5e7-4a20-b094-bfaa30eecef5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
