# Generated by Django 4.1 on 2022-08-20 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("492f7871-2efc-4374-ab90-257934fb9907"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
