# Generated by Django 4.1 on 2022-08-20 21:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("78ee0c68-8d61-49c5-b8fc-4140233f5d52"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
