# Generated by Django 4.1 on 2022-08-20 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e04da341-8e40-468c-a4bb-01469dd26179"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
